//! Generated gateway bootstrap for sdkwork-drive.
//! Regenerated by pnpm gateway:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use sdkwork_drive_http::infra::{drive_service_router_config, mount_drive_infra_routes};

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_business_router(pool: sqlx::AnyPool) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(
        sdkwork_routes_drive_app_api::gateway_mount_business(pool.clone()).await,
    );
    router = router.merge(
        sdkwork_routes_drive_backend_api::gateway_mount_business(pool.clone()).await,
    );
    router = router.merge(
        sdkwork_routes_drive_open_api::gateway_mount_business(pool.clone()).await,
    );
    ApplicationAssembly { router }
}

pub async fn assemble_application_router(pool: sqlx::AnyPool) -> ApplicationAssembly {
    let business = assemble_application_business_router(pool.clone()).await;
    let router = mount_drive_infra_routes(
        business.router,
        drive_service_router_config(&pool),
        Some("sdkwork-drive-gateway-assembly"),
    );
    ApplicationAssembly { router }
}
