//! Generated gateway bootstrap for sdkwork-drive.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use sqlx::AnyPool;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(pool: sqlx::AnyPool) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_drive_app_api::gateway_mount(pool.clone()).await);
    router = router.merge(sdkwork_routes_drive_backend_api::gateway_mount(pool.clone()).await);
    router = router.merge(sdkwork_routes_drive_open_api::gateway_mount(pool.clone()).await);
    ApplicationAssembly { router }
}
