packages:
  - 'packages/sdkwork-drive-*'
  - '../../../spring-ai-plus-app-api/sdkwork-sdk-app/sdkwork-app-sdk-typescript'
  - '../../../sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript'

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ~5.8.2
  vite: ^6.2.0

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
