#!/usr/bin/env python3
"""Generate http_route_manifest.rs from an OpenAPI document."""

from __future__ import annotations

import json
import sys
from pathlib import Path

METHOD_MAP = {
    "get": "Get",
    "post": "Post",
    "patch": "Patch",
    "delete": "Delete",
    "put": "Put",
}

AUTH_MAP = {
    "dual-token": "dual_token",
    "anonymous": "public",
    "refresh-token": "refresh_token",
    "api-key": "api_key",
    "oauth": "oauth",
    "open-api-flexible": "open_api_flexible",
    "internal": "public",
}


def load_routes(openapi_path: Path) -> list[tuple[str, str, str, str]]:
    document = json.loads(openapi_path.read_text(encoding="utf-8"))
    routes: list[tuple[str, str, str, str]] = []
    for path, methods in document.get("paths", {}).items():
        for method, operation in methods.items():
            if method not in METHOD_MAP:
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                raise ValueError(f"missing operationId for {method.upper()} {path}")
            auth_mode = operation.get("x-sdkwork-auth-mode", "dual-token")
            routes.append((method, path, operation_id, auth_mode))
    routes.sort(key=lambda item: (item[1], item[0]))
    return routes


def render(
    routes: list[tuple[str, str, str, str]],
    fn_name: str,
    tag: str,
) -> str:
    lines = [
        "// @generated by tools/gen_http_route_manifest_from_openapi.py — do not edit",
        "",
        "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
        "",
        "const HTTP_ROUTES: &[HttpRoute] = &[",
    ]
    for method, path, operation_id, auth_mode in routes:
        auth_fn = AUTH_MAP.get(auth_mode)
        if auth_fn is None:
            raise ValueError(f"unsupported auth mode {auth_mode!r} for {operation_id}")
        lines.extend(
            [
                f"    HttpRoute::{auth_fn}(",
                f"        HttpMethod::{METHOD_MAP[method]},",
                f'        "{path}",',
                f'        "{tag}",',
                f'        "{operation_id}",',
                "    ),",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            f"pub fn {fn_name}() -> HttpRouteManifest {{",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 5:
        print(
            "usage: gen_http_route_manifest_from_openapi.py "
            "<openapi.json> <output.rs> <fn_name> <tag>",
            file=sys.stderr,
        )
        return 1

    openapi_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    fn_name = sys.argv[3]
    tag = sys.argv[4]

    routes = load_routes(openapi_path)
    output_path.write_text(render(routes, fn_name, tag), encoding="utf-8")
    print(f"wrote {len(routes)} routes to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
